// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fapoowydvctlljbyarjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhcG9vd3lkdmN0bGxqYnlhcmptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMDg4MzQsImV4cCI6MjA2Mjc4NDgzNH0.i6MZBVxw3AMcCdLFy4dcnbj06HROwZmbmplofNbtWec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);